version: '3.9'
services:
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true
    depends_on:
      backend:
        condition: service_healthy
  backend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - ./backend:/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - ADMINNAME=admin
      - ADMINPASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/ping || exit 1
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 10s
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
    depends_on:
      backend:
        condition: service_healthy
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 1s
      retries: 5